name: Blocking Issues

on: 
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  pull_request_target: 
    types: [opened, edited, closed, reopened]
    
jobs: 
  blocking_issues: 
    runs-on: ubuntu-latest
    name: Checks for blocking issues
    
    steps: 
      - uses: Levi-Lesches/blocking-issues@v1
        with: 
          # Optional: Configure the label applied to blocked issues
          label-name: blocked
          label-color: 000000
          label-description: This PR is waiting for one or more issues to be closed.

